### ISSUE TITLE
Unable to Download Data Files

### ISSUE THREAD

**Issue by Wataru823** [tum-vision/DEVO#12]
First of all, thank you for sharing your excellent research code.

I am experiencing an issue with downloading data files from the provided URLs. Here are the details:

When I attempt to download the data file using the following command:

```sh
$ sh download_data.sh 
--2024-07-12 13:08:53--  https://cvg.cit.tum.de/webshare/g/evs/TartanAirEVS.pickle
Resolving cvg.cit.tum.de (cvg.cit.tum.de)... 131.159.19.110, 2a09:80c0:18::1110
Connecting to cvg.cit.tum.de (cvg.cit.tum.de)|131.159.19.110|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-07-12 13:08:55 ERROR 403: Forbidden.
```

I receive a `403 Forbidden` error. However, I am able to download the model file without any issues:

```sh
$ sh download_model.sh 
--2024-07-12 13:15:01--  https://cvg.cit.tum.de/webshare/g/evs/DEVO.pth
Resolving cvg.cit.tum.de (cvg.cit.tum.de)... 131.159.19.110, 2a09:80c0:18::1110
Connecting to cvg.cit.tum.de (cvg.cit.tum.de)|131.159.19.110|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 40902033 (39M)
Saving to: ‘DEVO.pth’

DEVO.pth             100%[======================>]  39.01M  5.36MB/s    in 8.6s    

2024-07-12 13:15:10 (4.56 MB/s) - ‘DEVO.pth’ saved [40902033/40902033]
```

The model file downloads successfully. I am also unable to download the training data in a similar manner.

Could you please share the data files, even if it's only a portion of them, through Google Drive or another method?

Thank you for your assistance.

### Related Issue
I couldn't reopen #9 , so I opened a new issue.

**Comment by motzet** [comment]
Hi,
Thank you for the issue.

The data file `TartanAirEVS.pickle` will be generated at the first run (training). I updated the Readme. Sorry for the confusion.

**Comment by Wataru823** [comment]
Thank you for updating the README!
