### ISSUE TITLE
Question about how event data is transformed into voxels.

### ISSUE THREAD

**Issue by Windaway** [tum-vision/DEVO#3]
Thank you for your contribution. I have a question about how event data is transformed into voxels. The paper mentions that voxel grids preserve temporal information by bilinear interpolation of event counts in time. It discretizes the time dimension into five bins and normalizes each voxel grid to zero mean and unit variance. However, I thought events themselves have only two states, on or off. How can they be saved as five bins?  Or did you accumulate both on and off states, directly summing up +1 and -1? Could you clarify this in advance?

**Comment by knelk** [comment]
We are using the vid2e code for that, see https://github.com/uzh-rpg/rpg_vid2e

I just added the script for creating the simulated events for tartan air
