### ISSUE TITLE
The official data file and the required file for the code are inconsistent

### ISSUE THREAD

**Issue by JaceLiu** [tum-vision/DEVO#4]
Thank you for your contribution. When evaluating your model using the UZH-FPV droneracing dataset, I noticed that the filenames in the dataset downloaded from the official website do not match those required by your code. For example, the official data has a file named "groundtruth.txt", while your code requires a file named "stamped_groundtruth_us_cam.txt". Additionally, the official dataset does not include files required by your code, such as "t_offset_us.txt", "rectify_map.h5", and "calib_undist.txt". Could you please advise on how to obtain these files and how the files mentioned in your code correspond to the official data?

**Comment by knelk** [comment]
It is computed in ```eDPVO/scripts/pp_rpg.py``` see https://github.com/tum-vision/DEVO/blob/main/scripts/pp_fpv.py#l131
