### ISSUE TITLE
I can't download the data

### ISSUE THREAD

**Issue by emrekeles-arch** [tum-vision/DEVO#9]
--2024-05-26 20:20:02--  (try: 2)  https://airlab-share.andrew.cmu.edu:8081/tartanair/abandonedfactory/Easy/depth_left.zip
Connecting to airlab-share.andrew.cmu.edu (airlab-share.andrew.cmu.edu)|128.237.74.70|:8081... failed: Connection timed out.
Retrying.

When I run download_training.py I get this warning and it keeps going. So i can't download the training data

**Comment by knelk** [comment]
ok there seems to be an issue with their server, please create an issue there. if not, reopen this isse
